"""Add contact management models

Revision ID: 06f460e7eefa
Revises: f71778487f5b
Create Date: 2025-10-31 13:18:00.545963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f460e7eefa'
down_revision = 'f71778487f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('successful_imports', sa.Integer(), nullable=True),
    sa.Column('failed_imports', sa.Integer(), nullable=True),
    sa.Column('duplicate_emails', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_imports_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_imports_status'), ['status'], unique=False)

    op.create_table('contact_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_lists_organization_id'), ['organization_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('lists', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='unique_contact_per_org')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_status'))
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_created_at'))

    op.drop_table('contacts')
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_lists_organization_id'))

    op.drop_table('contact_lists')
    with op.batch_alter_table('bulk_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_imports_status'))
        batch_op.drop_index(batch_op.f('ix_bulk_imports_organization_id'))

    op.drop_table('bulk_imports')
    # ### end Alembic commands ###
