"""Add campaign and template models

Revision ID: b5428fc553ee
Revises: 06f460e7eefa
Create Date: 2025-10-31 13:28:27.348682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5428fc553ee'
down_revision = '06f460e7eefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('segment_filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_delivered', sa.Integer(), nullable=True),
    sa.Column('emails_opened', sa.Integer(), nullable=True),
    sa.Column('emails_clicked', sa.Integer(), nullable=True),
    sa.Column('emails_bounced', sa.Integer(), nullable=True),
    sa.Column('emails_complained', sa.Integer(), nullable=True),
    sa.Column('emails_unsubscribed', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_contact_id'), ['contact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_contact_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))

    op.drop_table('campaign_recipients')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_organization_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_organization_id'))

    op.drop_table('email_templates')
    # ### end Alembic commands ###
